# Packages to install
packages=(
  # Terminal
  ghostty
  starship
  # Browser
  firefox
  # Dev tools
  neovim
  zellij
  git
  uv
  less
  gcc
	tar
  nodejs
  npm
  ripgrep
	tree-sitter-cli
  unzip
  docker
  # Environment
  gnome
  file-roller
  hyprland
  waybar
  hyprlauncher
  hyprpaper
  hyprlock
  hypridle
  xdg-desktop-portal-hyprland
  hyprshot
  ttf-jetbrains-mono-nerd
  qt6-svg 
  qt6-declarative 
  qt5-quickcontrols2
  pipewire
  wireplumber
  grim
  slurp
  # Nvidia
  nvidia-open
  nvidia-utils
  # Utils
  stow
  curl
  fastfetch
  noto-fonts-cjk
  ufw
  ntfs-3g
  ncdu
)
